// styles.ts (React Native)
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: '#f5f6fa',
  },
  contentContainer: {
    flexGrow: 1,
    padding: 16,
    ...Platform.select({
      web: {
        padding: 32,
      },
    }),
  },
  contentContainerCompact: {
    padding: 12,
  },
  contentContainerWide: {
    paddingHorizontal: 40,
  },
  container: {
    flex: 1,
    maxWidth: 1000,
    alignSelf: 'center',
    width: '100%',
  },
  profileHeader: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  profileHeaderWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 28,
  },
  avatarWrapper: {
    alignItems: 'center',
    marginBottom: 20,
    position: 'relative',
  },
  avatarWrapperWide: {
    marginBottom: 0,
    width: 150,
  },
  avatar: {
    width: 130,
    height: 130,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: '#f3f4f6',
  },
  avatarPlaceholder: {
    width: 130,
    height: 130,
    borderRadius: 24,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#f3f4f6',
  },
  avatarPlaceholderText: {
    fontSize: 48,
    color: 'white',
  },
  changePhotoBtn: {
    position: 'absolute',
    bottom: -8,
    right: -8,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
  },
  changePhotoBtnActive: {
    backgroundColor: '#94a3b8',
  },
  changePhotoBtnText: {
    fontSize: 14,
    color: 'white',
  },
  profileInfo: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  nameRowCompact: {
    alignItems: 'flex-start',
    gap: 12,
  },
  name: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1e293b',
  },
  nameCompact: {
    fontSize: 22,
    width: '100%',
  },
  badgeGroup: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 100,
    backgroundColor: '#f1f5f9',
  },
  badgeMotorista: {
    backgroundColor: '#4361ee10',
  },
  badgePassageiro: {
    backgroundColor: '#06d6a010',
  },
  badgeText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  ratingWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  ratingValue: {
    fontWeight: '800',
    fontSize: 20,
    color: '#f59e0b',
  },
  ratingCount: {
    fontSize: 13,
    color: '#64748b',
  },
  starFilled: {
    color: '#fbbf24',
    fontSize: 16,
  },
  starHalf: {
    color: '#fbbf24',
    fontSize: 16,
  },
  starEmpty: {
    color: '#d1d5db',
    fontSize: 16,
  },
  bio: {
    fontSize: 14,
    color: '#475569',
    lineHeight: 22,
    marginTop: 8,
  },
  editForm: {
    width: '100%',
  },
  formRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  formRowMobile: {
    flexDirection: 'column',
    gap: 0,
    marginBottom: 0,
  },
  formField: {
    flex: 1,
    marginBottom: 16,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
    color: '#334155',
  },
  formInput: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fafbfc',
    color: '#1e293b',
  },
  formTextarea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  editActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  editActionsCompact: {
    flexDirection: 'column',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#2563eb',
    borderRadius: 12,
  },
  saveButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 14,
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#f1f5f9',
    borderRadius: 12,
  },
  cancelButtonText: {
    color: '#475569',
    fontWeight: '700',
    fontSize: 14,
  },
  tabsScroll: {
    marginBottom: 20,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 8,
    backgroundColor: 'white',
    padding: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    minWidth: '100%',
  },
  tabsContainerWide: {
    width: '100%',
  },
  tabButton: {
    flex: 1,
    minWidth: 150,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
  },
  tabButtonCompact: {
    minWidth: 132,
    paddingHorizontal: 10,
  },
  tabButtonActive: {
    backgroundColor: '#2563eb',
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  tabButtonTextActive: {
    color: 'white',
  },
  tabContent: {
    minHeight: 400,
  },
  infoGrid: {
    gap: 16,
  },
  infoGridWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  infoCard: {
    flexDirection: 'row',
    gap: 16,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 12,
  },
  infoCardWide: {
    width: '50%',
    marginBottom: 16,
    marginHorizontal: 8,
    flexBasis: '47%',
  },
  infoIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIconText: {
    fontSize: 24,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#94a3b8',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    color: '#1e293b',
    fontWeight: '500',
  },
  changePasswordBtn: {
    marginTop: 10,
    color: '#2563eb',
    fontSize: 12,
    fontWeight: '600',
  },
  historicoContainer: {
    gap: 12,
  },
  historicoContainerWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  historicoCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    overflow: 'hidden',
    marginBottom: 12,
  },
  historicoCardWide: {
    width: '50%',
    marginHorizontal: 8,
    flexBasis: '47%',
  },
  historicoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  historicoType: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  historicoTypeOferecida: {
    backgroundColor: '#4361ee10',
  },
  historicoTypeParticipante: {
    backgroundColor: '#06d6a010',
  },
  historicoTypeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  historicoStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  historicoStatusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  historicoBody: {
    padding: 18,
  },
  historicoRoute: {
    marginBottom: 14,
  },
  routePoint: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  routeDotOrigin: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22c55e',
    marginTop: 4,
  },
  routeDotDestiny: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ef4444',
    marginTop: 4,
  },
  routeLine: {
    width: 2,
    height: 24,
    backgroundColor: '#e2e8f0',
    marginLeft: 5,
  },
  routeLabel: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '600',
  },
  routeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
    marginTop: 2,
  },
  historicoDetails: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#f1f5f9',
    marginBottom: 12,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detailText: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '500',
  },
  priceText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
  },
  historicoMotorista: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  motoristaText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '500',
  },
  historicoVagas: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  vagasText: {
    fontSize: 13,
    color: '#64748b',
    fontWeight: '500',
  },
  historicoButton: {
    paddingVertical: 12,
    backgroundColor: '#f8fafc',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    alignItems: 'center',
  },
  historicoButtonText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '600',
  },
  verMaisButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    marginTop: 8,
  },
  verMaisButtonWide: {
    width: '100%',
    marginHorizontal: 8,
  },
  verMaisText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 14,
  },
  avaliacoesContainer: {
    gap: 20,
  },
  avaliacoesSummary: {
    padding: 24,
    backgroundColor: 'white',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  avaliacoesSummaryWide: {
    flexDirection: 'row',
    gap: 28,
    alignItems: 'center',
  },
  summaryScore: {
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  summaryScoreWide: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
    minWidth: 160,
  },
  summaryScoreNumber: {
    fontSize: 48,
    fontWeight: '900',
    color: '#f59e0b',
  },
  summaryStars: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 10,
  },
  summaryTotal: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 6,
    fontWeight: '500',
  },
  summaryBreakdown: {
    gap: 10,
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  breakdownLabel: {
    fontSize: 13,
    width: 70,
  },
  breakdownBar: {
    flex: 1,
    height: 8,
    backgroundColor: '#f1f5f9',
    borderRadius: 4,
    overflow: 'hidden',
  },
  breakdownFill: {
    height: '100%',
    backgroundColor: '#f59e0b',
    borderRadius: 4,
  },
  breakdownCount: {
    fontSize: 13,
    width: 30,
    textAlign: 'right',
  },
  avaliacoesList: {
    gap: 12,
  },
  avaliacaoCard: {
    padding: 18,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  avaliacaoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  avaliacaoAutor: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avaliacaoAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avaliacaoAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: 'white',
  },
  avaliacaoNome: {
    fontWeight: '600',
    color: '#1e293b',
    fontSize: 14,
  },
  avaliacaoStars: {
    flexDirection: 'row',
    gap: 2,
    marginTop: 4,
  },
  avaliacaoData: {
    fontSize: 11,
    color: '#94a3b8',
  },
  avaliacaoComentario: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 20,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderStyle: 'dashed',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#64748b',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    width: '80%',
    maxWidth: 380,
  },
  modalIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  modalIconSuccess: {
    backgroundColor: '#10b98120',
  },
  modalIconError: {
    backgroundColor: '#ef444420',
  },
  modalIconText: {
    fontSize: 28,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    color: '#1e293b',
  },
  modalMessage: {
    fontSize: 13,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
  },
});
