import { Platform, StyleSheet } from 'react-native';

const shadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
  },
  android: {
    elevation: 5,
  },
  default: {},
});

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FAFAF7',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 28,
  },
  centerScreen: {
    flex: 1,
    backgroundColor: '#FAFAF7',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    marginTop: 14,
    color: '#64748B',
    fontSize: 15,
    fontWeight: '600',
  },
  hero: {
    minHeight: 230,
    backgroundColor: '#0A44B1',
    overflow: 'hidden',
    paddingTop: 48,
    paddingBottom: 92,
  },
  heroCircle: {
    position: 'absolute',
    top: -80,
    right: -58,
    width: 290,
    height: 290,
    borderRadius: 145,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  heroPattern: {
    position: 'absolute',
    left: 20,
    bottom: 32,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  heroInner: {
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    paddingHorizontal: 24,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 38,
    lineHeight: 44,
    fontWeight: '900',
    letterSpacing: 0,
  },
  heroSubtitle: {
    color: '#E8EE3B',
    marginTop: 7,
    fontSize: 15,
    fontWeight: '700',
  },
  content: {
    width: '100%',
    maxWidth: 1000,
    alignSelf: 'center',
    marginTop: -72,
    paddingHorizontal: 18,
  },
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#F5F5F4',
    padding: 22,
    marginBottom: 28,
    ...shadow,
  },
  profileCardWide: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 30,
  },
  profileMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  avatar: {
    width: 82,
    height: 82,
    borderRadius: 24,
    backgroundColor: '#0A44B1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
  },
  profileInfo: {
    flex: 1,
    minWidth: 0,
  },
  profileName: {
    color: '#1E293B',
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '900',
  },
  profileMeta: {
    marginTop: 8,
    gap: 7,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  metaText: {
    flex: 1,
    color: '#64748B',
    fontSize: 14,
    fontWeight: '600',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 11,
    paddingHorizontal: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  editButtonText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '800',
  },
  sectionTitle: {
    color: '#1E293B',
    fontSize: 25,
    fontWeight: '900',
    marginBottom: 18,
  },
  reservasGrid: {
    gap: 14,
  },
  reservasGridWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  reservaCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#F5F5F4',
    padding: 18,
  },
  reservaCardWide: {
    width: '48.5%',
    marginRight: '1.5%',
  },
  reservaHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 15,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '900',
  },
  statusConfirmada: {
    backgroundColor: '#D1FAE5',
  },
  statusConfirmadaText: {
    color: '#047857',
  },
  statusPendente: {
    backgroundColor: '#FEF3C7',
  },
  statusPendenteText: {
    color: '#B45309',
  },
  statusCancelada: {
    backgroundColor: '#FEE2E2',
  },
  statusCanceladaText: {
    color: '#B91C1C',
  },
  finalizadaBadge: {
    borderRadius: 999,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  finalizadaText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '900',
  },
  routeBox: {
    flexDirection: 'row',
    gap: 13,
    backgroundColor: '#FAFAF7',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  routeTimeline: {
    alignItems: 'center',
    paddingTop: 2,
  },
  originDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  routeLine: {
    width: 1,
    height: 28,
    backgroundColor: '#E5E7EB',
    marginVertical: 3,
  },
  destinationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0A44B1',
  },
  routeTexts: {
    flex: 1,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  routeOrigin: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '900',
  },
  routeDestination: {
    color: '#0A44B1',
    fontSize: 14,
    fontWeight: '900',
  },
  reservaDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detailText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
  },
  avaliarButton: {
    marginTop: 18,
    minHeight: 46,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#0A44B1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  avaliarButtonText: {
    color: '#0A44B1',
    fontSize: 14,
    fontWeight: '900',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    padding: 34,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: {
    color: '#334155',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 20,
    marginTop: 6,
    maxWidth: 330,
  },
  buscarButton: {
    marginTop: 22,
    backgroundColor: 'rgba(10,68,177,0.1)',
    borderRadius: 13,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buscarButtonText: {
    color: '#0A44B1',
    fontSize: 14,
    fontWeight: '900',
  },
  loggedOutCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#F5F5F4',
    alignItems: 'center',
    padding: 30,
    ...shadow,
  },
  loggedOutIcon: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: 'rgba(10,68,177,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  loggedOutTitle: {
    color: '#1E293B',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  loggedOutText: {
    color: '#64748B',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  ratingModal: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    alignItems: 'center',
    padding: 26,
    ...shadow,
  },
  modalClose: {
    position: 'absolute',
    top: 18,
    right: 18,
    zIndex: 1,
    padding: 6,
  },
  ratingIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(232,238,59,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: '#1E293B',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  modalDescription: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 22,
  },
  starsRow: {
    flexDirection: 'row',
    gap: 9,
    marginBottom: 22,
  },
  commentInput: {
    width: '100%',
    minHeight: 105,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#F5F5F4',
    backgroundColor: '#FAFAF7',
    padding: 14,
    color: '#1E293B',
    fontSize: 14,
    marginBottom: 18,
  },
  primaryModalButton: {
    width: '100%',
    minHeight: 50,
    borderRadius: 13,
    backgroundColor: '#0A44B1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryModalButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  editModal: {
    width: '100%',
    maxWidth: 500,
    maxHeight: '88%',
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    overflow: 'hidden',
    ...shadow,
  },
  editModalHeader: {
    minHeight: 64,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F4',
    backgroundColor: 'rgba(248,250,252,0.7)',
  },
  editModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editModalTitle: {
    color: '#1E293B',
    fontSize: 18,
    fontWeight: '900',
  },
  editModalBody: {
    padding: 22,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    padding: 12,
    marginBottom: 18,
  },
  errorText: {
    flex: 1,
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '700',
  },
  formField: {
    marginBottom: 16,
  },
  formLabel: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  inputWrapper: {
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 13,
  },
  textInput: {
    flex: 1,
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#F5F5F4',
    marginVertical: 4,
  },
  passwordTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    marginBottom: 16,
  },
  passwordTitle: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '900',
  },
  optionalText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
  },
  passwordInput: {
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    color: '#1E293B',
    paddingHorizontal: 14,
    fontSize: 14,
    fontWeight: '600',
  },
  editModalFooter: {
    padding: 22,
    backgroundColor: '#F8FAFC',
    borderTopWidth: 1,
    borderTopColor: '#F5F5F4',
  },
  saveChangesButton: {
    minHeight: 50,
    borderRadius: 13,
    backgroundColor: '#0A44B1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveChangesText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  passwordWrapper: {
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 14,
  },
  passwordEyeButton: {
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#F1F5F9',
    borderRadius: 16,
    padding: 4,
    marginBottom: 20,
    gap: 4,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
  },
  tabButtonActive: {
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  tabButtonText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
  },
  tabButtonTextActive: {
    color: '#0A44B1',
  },
  driverRideHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  driverRideHeaderTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0A44B1',
    textTransform: 'uppercase',
  },
  vagasBadge: {
    backgroundColor: 'rgba(10,68,177,0.06)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 99,
  },
  vagasBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#0A44B1',
  },
  requestsSection: {
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 15,
  },
  requestsTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#475569',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  noRequestsText: {
    fontSize: 13,
    color: '#94A3B8',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 10,
  },
  requestsList: {
    gap: 10,
  },
  requestItemCard: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 12,
  },
  passengerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  passengerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#0A44B1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  passengerAvatarText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  passengerMeta: {
    flex: 1,
    minWidth: 0,
  },
  passengerNameText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1e293b',
  },
  passengerSubText: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 1,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 10,
  },
  approveButton: {
    flex: 1,
    flexDirection: 'row',
    height: 38,
    backgroundColor: '#10B981',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  approveButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  rejectButton: {
    flex: 1,
    flexDirection: 'row',
    height: 38,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  rejectButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  profileActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 18,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 11,
    paddingHorizontal: 16,
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  logoutButtonText: {
    color: '#EF4444',
    fontSize: 14,
    fontWeight: '800',
  },
});
