import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../../theme';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  map: {
    width: width,
    height: height,
  },
  searchContainer: {
    position: 'absolute',
    top: 20,
    width: '100%',
    paddingHorizontal: 20,
    zIndex: 1,
  },
  searchCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 5 },
  },
  markerDecoration: {
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.primary,
  },
  line: {
    width: 1,
    height: 30,
    backgroundColor: '#ccc',
    marginVertical: 4,
  },
  square: {
    width: 6,
    height: 6,
    backgroundColor: '#000',
  },
  inputsContainer: {
    flex: 1,
  },
  inputWrapper: {
    marginBottom: 5,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    padding: 20,
    paddingBottom: 40,
    backgroundColor: 'transparent',
  },
  priceCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -5 },
  },
  confirmButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 12,
  },
  textInput: {
    height: 40,
    fontSize: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginTop: 5,
  },
  resultsList: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginTop: 10,
    maxHeight: 200,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  resultItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '88%',
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    overflow: 'hidden',
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  modalHeader: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F4',
    paddingHorizontal: 22,
  },
  modalTitle: {
    color: '#1E293B',
    fontSize: 20,
    fontWeight: '900',
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    padding: 22,
  },
  modalScroll: {
    maxHeight: 350,
  },
  rideOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#FAFAF7',
    padding: 15,
    marginBottom: 12,
  },
  rideOptionCardSelected: {
    borderColor: '#0A44B1',
    backgroundColor: 'rgba(10,68,177,0.05)',
  },
  rideDriverAvatar: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#0A44B1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rideDriverAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  rideDetails: {
    flex: 1,
  },
  rideDriverName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1E293B',
  },
  rideDriverUni: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  rideMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 5,
  },
  rideMetaText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
  },
  ridePrice: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0A44B1',
    marginLeft: 10,
  },
  noRidesText: {
    textAlign: 'center',
    color: '#64748B',
    fontSize: 16,
    marginVertical: 30,
  },
  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: '#F5F5F4',
    backgroundColor: '#F8FAFC',
    padding: 22,
    gap: 10,
  },
  reserveButton: {
    minHeight: 54,
    borderRadius: 18,
    backgroundColor: '#0A44B1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  reserveButtonDisabled: {
    opacity: 0.6,
  },
  reserveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  modalFooterNote: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
});

export const autocompleteStyles = {
  container: { flex: 0 },
  textInput: {
    height: 40,
    fontSize: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  listView: {
    position: 'absolute',
    top: 45,
    backgroundColor: '#fff',
    borderRadius: 10,
    elevation: 5,
    zIndex: 1000,
  }
};
