import { Platform, StyleSheet } from 'react-native';

const blue = '#0A44B1';
const yellow = '#E8EE3B';

const shadow = Platform.select({
  ios: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  android: {
    elevation: 4,
  },
  default: {},
});

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: '#FAFAF7',
  },
  scroll: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 28,
  },
  hero: {
    backgroundColor: blue,
    overflow: 'hidden',
    paddingBottom: 70,
    paddingTop: 44,
  },
  heroCircle: {
    position: 'absolute',
    right: -40,
    top: -60,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  heroYellowCircle: {
    position: 'absolute',
    left: 34,
    bottom: -76,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(232,238,59,0.08)',
  },
  heroInner: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    paddingHorizontal: 22,
  },
  heroTop: {
    gap: 18,
  },
  heroTextBlock: {
    flex: 1,
  },
  badge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(232,238,59,0.4)',
    backgroundColor: 'rgba(232,238,59,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 14,
  },
  badgeText: {
    color: yellow,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  titulo: {
    color: '#FFFFFF',
    fontSize: 38,
    lineHeight: 44,
    fontWeight: '900',
    letterSpacing: 0,
  },
  tituloCompact: {
    fontSize: 32,
    lineHeight: 38,
  },
  subtitulo: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '600',
    marginTop: 8,
  },
  counterBox: {
    alignSelf: 'center',
    minWidth: 138,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 20,
    paddingVertical: 13,
  },
  counterNumber: {
    color: '#FFFFFF',
    fontSize: 32,
    lineHeight: 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  counterText: {
    color: 'rgba(255,255,255,0.64)',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 3,
    textAlign: 'center',
  },
  container: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
    marginTop: -34,
    paddingHorizontal: 16,
  },
  filtros: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(229,231,235,0.8)',
    borderRadius: 28,
    borderWidth: 1,
    padding: 16,
    marginBottom: 24,
    ...shadow,
  },
  filterRow: {
    gap: 12,
  },
  filterRowWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  field: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 9,
  },
  fieldFocused: {
    borderColor: blue,
    backgroundColor: '#FFFFFF',
  },
  fieldWide: {
    flex: 1,
    minWidth: 180,
  },
  dateFieldWide: {
    minWidth: 160,
  },
  fieldIcon: {
    width: 18,
  },
  input: {
    flex: 1,
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '700',
    minHeight: 46,
    paddingVertical: 0,
  },
  arrowDivider: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(10,68,177,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vagasToggle: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  vagasToggleActive: {
    borderColor: blue,
    backgroundColor: 'rgba(10,68,177,0.05)',
  },
  vagasToggleText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
  },
  vagasToggleTextActive: {
    color: blue,
  },
  clearButton: {
    minHeight: 50,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 16,
  },
  clearButtonText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '800',
  },
  activeFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 22,
  },
  filterPill: {
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(10,68,177,0.15)',
    backgroundColor: 'rgba(10,68,177,0.08)',
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  filterPillHighlight: {
    borderColor: 'rgba(232,238,59,0.6)',
    backgroundColor: 'rgba(232,238,59,0.3)',
  },
  filterPillText: {
    color: blue,
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 190,
  },
  filterPillTextHighlight: {
    color: '#6B5E00',
  },
  grid: {
    gap: 18,
  },
  gridWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -10,
  },
  cardColumn: {
    width: '100%',
  },
  cardColumnTablet: {
    width: '50%',
    paddingHorizontal: 10,
  },
  cardColumnWide: {
    width: '33.3333%',
  },
  skeletonCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#F5F5F4',
    padding: 20,
    gap: 16,
  },
  skeletonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  skeletonAvatar: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
  },
  skeletonLines: {
    flex: 1,
    gap: 8,
  },
  skeletonLineLarge: {
    height: 15,
    width: '76%',
    borderRadius: 8,
    backgroundColor: '#E2E8F0',
  },
  skeletonLineSmall: {
    height: 12,
    width: '52%',
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  skeletonRoute: {
    height: 96,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
  },
  skeletonInfoRow: {
    flexDirection: 'row',
    gap: 8,
  },
  skeletonInfo: {
    flex: 1,
    height: 56,
    borderRadius: 13,
    backgroundColor: '#F1F5F9',
  },
  skeletonButton: {
    height: 48,
    borderRadius: 18,
    backgroundColor: '#E2E8F0',
  },
  stateBlock: {
    alignItems: 'center',
    paddingVertical: 68,
    paddingHorizontal: 24,
  },
  errorIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(10,68,177,0.1)',
    backgroundColor: 'rgba(10,68,177,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  stateTitle: {
    color: '#334155',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 7,
  },
  emptyTitle: {
    color: '#1E293B',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 8,
  },
  stateText: {
    color: '#94A3B8',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 360,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 18,
    borderRadius: 18,
    backgroundColor: blue,
    paddingHorizontal: 22,
    paddingVertical: 13,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  emptyClearButton: {
    marginTop: 18,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: blue,
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  emptyClearText: {
    color: blue,
    fontSize: 14,
    fontWeight: '900',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    width: '100%',
    maxWidth: 520,
    maxHeight: '88%',
    backgroundColor: '#FFFFFF',
    borderRadius: 32,
    overflow: 'hidden',
    ...shadow,
  },
  modalHeader: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F4',
    paddingHorizontal: 22,
  },
  modalTitle: {
    color: '#1E293B',
    fontSize: 20,
    fontWeight: '900',
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    padding: 22,
  },
  driverInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F5F5F4',
    backgroundColor: '#FAFAF7',
    padding: 15,
    marginBottom: 22,
  },
  modalAvatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  driverInfoText: {
    flex: 1,
    minWidth: 0,
  },
  modalDriverName: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '900',
  },
  modalUniversity: {
    color: blue,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  modalRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 5,
  },
  modalRatingText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '900',
  },
  modalRoute: {
    position: 'relative',
    gap: 20,
    marginBottom: 22,
  },
  modalRouteLine: {
    position: 'absolute',
    left: 19,
    top: 30,
    bottom: 30,
    width: 2,
    backgroundColor: '#E5E7EB',
  },
  modalRoutePoint: {
    flexDirection: 'row',
    gap: 14,
  },
  modalOriginIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#D1FAE5',
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOriginDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
  },
  modalDestinationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(10,68,177,0.2)',
    backgroundColor: 'rgba(10,68,177,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalRouteTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalRouteLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  modalRouteText: {
    color: '#1E293B',
    fontSize: 16,
    fontWeight: '800',
  },
  modalRouteDestination: {
    color: blue,
    fontSize: 16,
    fontWeight: '800',
  },
  modalInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 22,
  },
  modalInfoCard: {
    width: '48%',
    minHeight: 78,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F5F5F4',
    backgroundColor: '#FAFAF7',
    padding: 13,
    justifyContent: 'center',
  },
  modalInfoLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  modalInfoValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  modalInfoValue: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '900',
  },
  modalPrice: {
    color: blue,
    fontSize: 17,
    fontWeight: '900',
  },
  modalWarning: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(10,68,177,0.1)',
    backgroundColor: 'rgba(10,68,177,0.05)',
    padding: 15,
    marginBottom: 10,
  },
  modalWarningTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  modalWarningLabel: {
    color: blue,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  modalWarningText: {
    color: '#334155',
    fontSize: 14,
    lineHeight: 20,
  },
  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: '#F5F5F4',
    backgroundColor: '#F8FAFC',
    padding: 22,
  },
  reserveButton: {
    minHeight: 54,
    borderRadius: 18,
    backgroundColor: blue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  reserveButtonDisabled: {
    opacity: 0.6,
  },
  reserveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  modalFooterNote: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 11,
  },
});
